###订单服务的端口号
server:
  port: 7100

###注册到注册中心的服务的名字
spring:
   application:
    name: app-itmayiedu-order
    
    
    
eureka:
  client: 
    service-url:
       ###当前会员服务注册到eureka服务的地址
       defaultZone: http://localhost:9100/eureka
    ###需要将我的服务注册到eureka上
    register-with-eureka: true
    ###表示服务需要检索
    fetch-registry: true



#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
#
####开启hystrix注解
#feign:
#  hystrix:
#    enabled: true

###禁止超时时间 
#hystrix: 
#  command: 
#    default: 
#      execution: 
#        timeout: 
#          enabled: false
    
    


       